markdown: kramdown
theme: jekyll-theme-cayman
title: MaryEllenTeaches.Me
description: spring, mvc, spring-data-repositories, jpa, mongodb, reactive, rest, docker, jdbc 
github:
  is_project_page: true
  repository_url: https://github.com/maryellenteaches
